#!/usr/bin/env sh
TARGET_DIR=$1
HOST_REPO=$(pwd)
DEST_REPO=$2
STASH_TEMP=$(uuidgen)

HOST_REPO_CHANGES="$(git status --porcelain)"
if [ "$HOST_REPO_CHANGES" ]; then
    git stash save -u $STASH_TEMP
fi

cd "$DEST_REPO"
DEST_REPO_CHANGES="$(git status --porcelain)"
if [ "$DEST_REPO_CHANGES" ]; then
    git stash save -u $STASH_TEMP
fi
git pull
latest_commit_msg=$(git show --no-patch --oneline $(git rev-list -1 HEAD))
cd "$HOST_REPO"
git pull
#copy
rsync -av --exclude=.git* $DEST_REPO/* $HOST_REPO/$TARGET_DIR
git add .
git commit -m "$latest_commit_msg"
cd "$DEST_REPO"
if [ "$DEST_REPO_CHANGES" ]; then
    git stash apply "stash^{/$STASH_TEMP}"
fi
cd -
if [ "$HOST_REPO_CHANGES" ]; then
    git stash apply "stash^{/$STASH_TEMP}"
fi
