#!/usr/bin/env sh
TARGET_DIR=$1
HOST_REPO=$(pwd)
DEST_REPO=$2
STASH_TEMP=$(uuidgen)

HOST_REPO_CHANGES="$(git status --porcelain)"
if [ "$HOST_REPO_CHANGES" ]; then
    git stash save -u $STASH_TEMP
fi
cd "$DEST_REPO"
DEST_REPO_CHANGES="$(git status --porcelain)"
if [ "$DEST_REPO_CHANGES" ]; then
    git stash save -u $STASH_TEMP
fi
cd "$HOST_REPO"
rsync -av --exclude=.git* $HOST_REPO/$TARGET_DIR/* $DEST_REPO
latest_commit_msg=$(git show --no-patch --oneline $(git rev-list -1 HEAD -- "$TARGET_DIR"))
cd "$DEST_REPO"
git add .
git commit -m "$latest_commit_msg"
if [ "$DEST_REPO_CHANGES" ]; then
    git stash apply "stash^{/$STASH_TEMP}"
fi
cd $HOST_REPO
if [ "$HOST_REPO_CHANGES" ]; then
    git stash apply "stash^{/$STASH_TEMP}"
fi
