#!/usr/bin/env sh

usage() {
	echo "usage: git subfile <command> [params ...]"
	echo
	echo "commands:"
	echo "write [relative path of target in current repo] [absolute path for original repo]"
	echo "read [relative path of target in current repo] [absolute path for original repo]"
	echo
	echo "examples:"
	echo "git subfile write src/target/path ~/Documents/MyProjectAsSubtree"
	echo "git subfile read src/target/path ~/Documents/MyProjectAsSubtree"
	echo
}

version() {
	echo "0.0.1"
}

main() {
	if [ "$#" -lt 1 ]; then
		usage; exit 1
	fi

	local subcommand="$1"; shift
    case $subcommand in
		"-h"|"--help")
			usage; exit 0
			;;
		"-v"|"--version")
			version; exit 0
			;;
	esac

	local workingdir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
    echo "$workingdir/git-subfile-$subcommand"
	if [ ! -e "$workingdir/git-subfile-$subcommand" ]; then
		usage; exit 1
	fi

	source "$workingdir/git-subfile-$subcommand" "$@"
}
main "$@"
