#!/usr/bin/env osascript -l JavaScript

// based on private api for >= iTunes 12.4

var log = console.log

cleanTrackLists()

function cleanTrackLists(){
	iTunes = Application('iTunes')
	delay(.3)

	var cleancount = 0
	var albums = {}
	var files = {}
	var targetTracks = iTunes.libraryPlaylists[0].fileTracks();
	if(targetTracks.length>0){
		log('Now cleaning...');
		for(var t in targetTracks){
			//'t' is just an index(Int) since iTunes 12.4. Why???
			t = targetTracks[t]

			// track.podcast() is deprecated.. sucks.
			// if(t.podcast()){
			// 	return;
			// }

			//clean by file location
			var loc = t.location()
			var cleanByFile = !loc || (loc && files[loc])

			//clean byname by same album
			var an = t.album()
			var cleanByNameInAlbum = (albums[an] ? albums[an] : (albums[an]={}))[t.name()]
			var shouldDelete = cleanByFile || cleanByNameInAlbum

			if(shouldDelete) console.log(t.name())

			if(shouldDelete){
				iTunes.delete(t)
				cleancount++
			}else{
				files[loc] = t
				albums[an][t.name()] = t
			}
		}
	}else{
		log('Not found any songs in your itunes library.');
	}

	return cleancount
}
